
require 'rubygems'
require 'json/pure'
require 'rake'
require 'pathname'
require 'crxmake'

project_name = '<%= target_name %>'

github_account = 'youracountname' # `git config github.user`.chomp
github_project = '<%= target_name %>'
extension_url = "http://cloud.github.com/downloads/#{github_account}/#{github_project}/#{project_name}.crx"

root_path = Pathname.new(__FILE__).parent
src_path = root_path.join('src')
manifest_path = src_path.join('manifest.json')
update_path = src_path.join('update.xml')
output_path = root_path.join('bin')
pem_file = ENV['PEM'] || root_path.join(project_name + '.pem')

task :release => [:update_xml, :package]
task :default => [:release]

task :update_xml do
  puts "update xml: #{update_path}"
  manifest = JSON.parse manifest_path.read
  raise 'require id & version' unless manifest['id'] && manifest['version']
  template = <<-EOF
<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
    <app appid="#{manifest['id']}">
        <updatecheck codebase="#{extension_url}" version="#{manifest['version']}" />
    </app>
</gupdate>
  EOF
  update_path.open('w') do |f|
    f.puts template
  end
end

task :package do
  output_path.mkpath unless output_path.directory?
  crx = output_path.join("#{project_name}.crx").to_s
  options = {
    :ex_dir => src_path.to_s,
    :crx_output => crx,
#    :verbose => true,
    :ignorefile => /\.sw[op]/,
    :ignoredir => /\.(?:svn|git|cvs)/
  }
  if pem_file && Pathname.new(pem_file.to_s).exist?
    options[:pkey] = pem_file.to_s
  else
    options[:pkey_output] = pem_file.to_s
  end
  CrxMake.make(options)
  puts "generated package: #{crx}"
  puts "generated pkem(.pem): #{options[:pkey_output]}" if options[:pkey_output]
end

